set(_CATKIN_CURRENT_PACKAGE "vision_neural_net")
set(vision_neural_net_VERSION "0.0.0")
set(vision_neural_net_MAINTAINER "nick <nick@todo.todo>")
set(vision_neural_net_PACKAGE_FORMAT "1")
set(vision_neural_net_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(vision_neural_net_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(vision_neural_net_BUILDTOOL_DEPENDS "catkin")
set(vision_neural_net_BUILDTOOL_EXPORT_DEPENDS )
set(vision_neural_net_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(vision_neural_net_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(vision_neural_net_TEST_DEPENDS )
set(vision_neural_net_DOC_DEPENDS )
set(vision_neural_net_DEPRECATED "")